### ISSUE TITLE
非常非常非常抱歉我用这种方式打扰到您

### ISSUE THREAD

**Issue by Asakushen** [dajia-1701/VJudge-Boost#1]
我想询问的是关于您的站点[blog](https://www.d0j1a1701.cc/)的站点地图sitemap是否有成功提交到谷歌呢？采取了什么方法最后成功了呢？【我注意到您在很久之前询问过为何站点地图提交失败的问题，我也遇到同样的问题】。再次为我的到来感到抱歉，我找遍了您的所有网站都未能发现其他的联系方式，不得已采取在这个issue里和你交流非此仓库的问题。感谢您的解答。

**Comment by Ikaleio** [comment]
> 我想询问的是关于您的站点[blog](https://www.d0j1a1701.cc/)的站点地图sitemap是否有成功提交到谷歌呢？采取了什么方法最后成功了呢？【我注意到您在很久之前询问过为何站点地图提交失败的问题，我也遇到同样的问题】。再次为我的到来感到抱歉，我找遍了您的所有网站都未能发现其他的联系方式，不得已采取在这个issue里和你交流非此仓库的问题。感谢您的解答。

找到这里来了（

但是很抱歉，我只是等了几天就自己好了 :(
